---
- name: Update package cache
  become: yes
  package:
    update_cache: yes

- name: Install nginx
  become: yes
  with_items: "{{ centos_nginx_packages }}"
  package:
    pkg: "{{ item.name }}"
    state: latest

- name: Setup template Nginx.conf
  become: yes
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root

- name: Create sites-available
  become: yes
  file:
    path: /etc/nginx/sites-available/
    state: directory
    mode: 0755

- name: Create sites-enabled
  become: yes
  file:
    path: /etc/nginx/sites-enabled/
    state: directory
    mode: 0755

- name: Update nginx confs for WordPress + PHP
  become: yes
  template:
    src: ../templates/centos-default-site.conf
    dest: /etc/nginx/sites-available/{{server_hostname}}.conf
    owner: "{{server_hostname}}"
    group: "{{server_hostname}}"
    mode: 0644


- name: setup for enabling site
  become: yes
  file:
    src: /etc/nginx/sites-available/{{server_hostname}}.conf
    dest: /etc/nginx/sites-enabled/{{server_hostname}}.conf
    owner: "{{server_hostname}}"
    group: "{{server_hostname}}"
    state: link

- name: set http in firewall
  become: yes
  firewalld:
    service: http
    permanent: yes
    zone: public
    state: enabled

- name: set tcp in firewall
  become: yes
  firewalld:
    port: 443/tcp
    permanent: yes
    zone: public
    state: enabled

- name: Reload firewall
  become: yes
  service:
    name: firewalld
    state: restarted

- name: Restart Nginx
  become: yes
  service:
    name: nginx
    state: restarted
