---
- name: Update package cache
  become: yes
  package:
    update_cache: yes
    cache_valid_time: 3600

- name: Install nginx
  become: yes
  with_items: "{{ fedora_nginx_packages }}"
  package:
    pkg: "{{ item.name }}"
    state: latest


- name: Create sites-available
  become: yes
  path: /etc/nginx/sites-available/
  state: directory
  mode: 0755


- name: Update nginx confs for WordPress + PHP
  become: yes
  template:
    src: ../templates/default-site.conf
    dest: /etc/nginx/sites-available/{{server_hostname}}
    owner: {{server_hostname}}
    group: {{server_hostname}}
    mode: 0644


- name: setup for enabling site
  become: yes
  file:
    src: /etc/nginx/sites-available/{{server_hostname}}
    dest: /etc/nginx/sites-enabled/{{server_hostname}}
    owner: {{server_hostname}}
    group: {{server_hostname}}
    state: link

- name: Restart Nginx
  become: yes
  service:
    name: nginx
    state: restarted
