---

- name: Install postfix
  become: yes
  with_items: "{{ postfix_packages }}"
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: Start postfix
  become: yes
  service: name=postfix state=started enabled=yes
