---

- name: Install php extensions
  become: yes
  with_items: "{{ fedora_php_packages }}"
  package:
    pkg: "{{ item.name }}"
    state: present

- name: Create backup php.ini
  become: yes
  copy:
    src: "/etc/php.ini"
    dest: "/etc/php.ini.bak"
    owner: root
    group: root
    remote_src: yes

- name: Setup php-fpm
  become: yes
  replace:
    dest: /etc/php.ini
    regexp: "(;cgi.fix_pathinfo=1)"
    replace: "cgi.fix_pathinfo=0"

- name: restart php-fpm
  become: yes
  service:
    name: php-fpm
    state: restarted
