---
- name: Update apt cache
  become: yes
  apt: update_cache=yes cache_valid_time=86400

- name: Install depends
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - python3
    - python3-dev
    - gcc
    - dialog
    - libaugeas0
    - augeas-lenses
    - libssl-dev
    - libffi-dev
    - ca-certificates
    - python3-pip
    - python3-virtualenv
    - git
    - libpython3-dev
    - zlib1g-dev

- name: Lets Encrypt client
  become: yes
  git: dest=/opt/certbot clone=yes repo=https://github.com/certbot/certbot force=yes

- name: Create certificate
  become: yes
  shell: ./certbot-auto certonly --webroot --email {{ letsencrypt_email}} --agree-tos --webroot-path=/usr/share/nginx/html -d {{ server_hostname }};
  args:
    chdir: /opt/certbot

- name: Add crontab to renew certificates
  become: yes
  cron: minute="30" hour="2" weekday="1" job="/opt/certbot/certbot-auto renew >> /var/log/le-renew.log"

- name: Add crontab to reload server
  become: yes
  cron: minute="35" hour="2" weekday="1" job="/etc/init.d/nginx reload"

